# Generated by Django 3.1.2 on 2020-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='purpose',
            field=models.CharField(choices=[('Main', 'Main'), ('Sub', 'Sub')], default='Sub', max_length=224),
        ),
    ]
