# Generated by Django 3.1.2 on 2020-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_filemodel_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='purpose',
        ),
        migrations.CreateModel(
            name='SubFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='/Users/khangtu/PycharmProjects/spam/media/image', path='/media/image')),
            ],
            options={
                'unique_together': {('file', 'path')},
            },
        ),
    ]
