# Generated by Django 3.1.2 on 2020-11-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_auto_20201121_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubFileModel',
        ),
    ]
