# Generated by Django 3.1.2 on 2020-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileHdrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('expose_time', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='/Users/khangtu/PycharmProjects/spam/media', path='/Users/khangtu/PycharmProjects/spam/media')),
            ],
            options={
                'unique_together': {('file', 'path')},
            },
        ),
    ]
